---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: coinbase-auto-transfer
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
            - name: coinbase-auto-transfer
              image: coinbase-auto-transfer
              imagePullPolicy: IfNotPresent
              env:
                - name: COINBASE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: COINBASE_API_KEY
                - name: COINBASE_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: COINBASE_API_SECRET
                - name: BITCOIN_WALLET
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: BITCOIN_WALLET
