---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: coinbase-auto-withdraw
spec:
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1 
  suspend: false 
  concurrencyPolicy: Forbid 
  schedule: "@hourly"
  jobTemplate:
    spec:
      parallelism: 1 
      completions: 1 
      backoffLimit: 3 
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
            - name: coinbase-auto-withdraw
              image: localhost:32000/coinbase-auto-withdraw:0.0.1
              env:
                - name: COINBASE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: COINBASE_API_KEY
                - name: COINBASE_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: COINBASE_API_SECRET
                # - name: BITCOIN_WALLET
                #   valueFrom:
                #     secretKeyRef:
                #       name: coinbase
                #       key: BITCOIN_WALLET
                - name: XPUB_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: coinbase
                      key: XPUB_ADDRESS
